20 guideextras
vuejs-translations/docs-it pull request #110
Opened 2023-09-09 13:14 UTC by andreacampaci

## Description of Problem
File da tradurre:

- [ ] guide/extras
  - [x ] animation.md
  - [x ] composition-api-faq.md
  - [x ] demos
    - [ x] AnimateWatcher.vue
    - [x ] Colors.vue
    - [x ] DisabledButton.vue
    - [ x] ElasticHeader.vue
    - [ x] SpreadSheet.vue
    - [ x] SpreadSheetCell.vue
    - [ x] spreadSheetStore.js
  - [ x] reactivity-in-depth.md
  - [ x] reactivity-transform.md
  - [ ] render-function.md
  - [ ] rendering-mechanism.md
  - [ x] ways-of-using-vue.md
  - [ ] web-components.md

2023-09-16 10:18 UTC, phox081 commented
@andreacampaci c'è qualche problema con i controlli di netlify

2023-10-07 12:44 UTC, phox081 requested changes

2023-10-07 14:13 UTC, andreacampaci commented on src/guide/extras/reactivity-transform.md
> +- Richiede `@vitejs/plugin-vue@>=2.0.0`
sistemato

2023-10-07 14:13 UTC, andreacampaci commented on src/guide/extras/animation.md
> +## Animazione con gli osservatori {#animating-with-watchers}
sistemato

2023-10-07 14:13 UTC, andreacampaci commented on src/guide/extras/animation.md
> +Oltre al colore, puoi anche utilizzare le associazioni di stile per animare la trasformazione, la larghezza o l'altezza di un elemento. Puoi anche animare percorsi SVG utilizzando la conformazione ve
sistemato

2023-10-07 14:14 UTC, andreacampaci commented on src/guide/extras/animation.md
> +
sistemato

2023-10-07 14:14 UTC, andreacampaci commented on src/guide/extras/reactivity-transform.md
> +
sistemato

2023-10-07 14:16 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Noi crediamo alla storia che c'è un modo giusto in assoluto che vada per tutti nel mondo del web. Questo è il principale motivo per la quale abbiamo disegnato Vue per essere versatile e flessibile. A
sistemato

2023-10-07 14:16 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Vue può essere utilizzato con script file "standalone", ovvero senza necessità di build. Se hai un framework backend che già renderizza la maggior parte del HTML, o la tua logica di frontend non è co
sistemato

2023-10-07 14:17 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Inoltre Vue dispone di una distribuzione alternativa chiamata [petite-vue](https://github.com/vuejs/petite-vue) che è specificatamente ottimizzata per migliorare progressivamente il codice HTML esist
sistemato

2023-10-07 14:18 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +## Utilizzare Web Components {#embedded-web-components}
sistemato

2023-10-07 14:18 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Puoi usare Vue per [creare Web Components nativi](/guide/extras/web-components) che potrai embeddare in ogni pagina HTML, indipendentemente da come quest'ultime vengano renderizzate. Questa opzione t
sistemato

2023-10-07 14:19 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
>  ## Single-Page Application (SPA) {#single-page-application-spa}
sistemato

2023-10-07 14:20 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Molte delle applicazioni richiedono molta interattività, gestione della sessione, e una logica stateful complessa lato frontend. Il modo migliore per creare applicazioni è di usare un architettura do
sistemato

2023-10-07 14:20 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Per rendere ancora più piacevole l'esperienza di sviluppo, Vue dispone di librerie core e [strumenti di supporto completo](/guide/scaling-up/tooling) che  includono:
sistemato

2023-10-07 14:21 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Client-side router
sistemato

2023-10-07 14:21 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Blazing fast build tool chain (Strumenti di costruzione delle applicazioni incredibilmente veloce)
sistemato

2023-10-07 14:23 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Blazing fast build tool chain (Strumenti di costruzione delle applicazioni incredibilmente veloce)
sistemato

2023-10-07 14:23 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Tipicamente le SPA richiedono un backend che espone API, ma soluzioni come [Inertia.js](https://inertiajs.com) possono essere abbinate a Vue per avere i vantaggi di una SPA ma mantenere il modello di
sistemato

2023-10-07 14:23 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Le SPA "pure" sono limitate quando le applicazioni devono essere soggette a pratiche SEO e time-to-content. Questo perché il browser riceverà una pagina HTML gran parte vuota, e deve aspettare fino a
sistemato

2023-10-07 14:24 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Vue dispone di API di prima categoria per "renderizzare" lato Sever una Vue app in stringhe HTML. Questo fa si che il server risponda con il codice HTML già renderizzato, così che l'utente finale ved
sistemato

2023-10-07 14:25 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Esistono Framework che si basano su Vue costruiti su questo paradigma, come [Nuxt](https://nuxt.com/), che fa si che tu possa sviluppare una fullstack application utilizzando Vue e Javascript.
sistemato

2023-10-07 14:26 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Il rendering lato server può essere eseguito in anticipo se i dati sono statici. Questo significa che noi possiamo pre-renderizzare un intera applicazione in HTML e distribuirla come file statici. Qu
sistemato

2023-10-07 14:26 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Ci sono due tipi di SSG: single-page e multi-page.Tutte e due le tipologie pre-renderizzano il sito in HTML statico, la differenza è la seguente:
sistemato

2023-10-07 14:26 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Dopo che la pagina iniziale è caricata , una single-page SSG verrà sostituita con una SPA. Questo richiede un costo in termini di tempo di caricamento e di "hydration", ma dopo di questo le navigaz
sistemato

2023-10-07 14:27 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Una multi-page SSG caricherà una nuova pagina ogni navigazione. Il lato positivo è che verrà caricato il solo JS necessario - o potrebbe non caricare JS se tutte le pagine caricate non hanno intera
sistemato

2023-10-07 14:27 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Le applicazioni Single-page SSG è la migliore soluzione se ti aspetti un interazione significativa, gestione della sessione o elementi persistenti / stato applicativo cross navigazione. Altrimenti, l
sistemato

2023-10-07 14:29 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Il team di Vue mantiene anche uno static-site generator chiamato [VitePress](https://vitepress.dev/), su cui è costruito questo sito Web che stai leggendo in questo momento! VitePress supporto tutte
sistemato

2023-10-07 14:29 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +## Oltre al web {#beyond-the-web}
sistemato

2023-10-07 14:29 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +Sebbene Vue sia progettato principalmente per la creazione di applicazioni web, non è limitato ad esso. Puoi:
sistemato

2023-10-07 14:31 UTC, andreacampaci commented on src/guide/extras/ways-of-using-vue.md
> +- Utilizzare Vue come [Custom Renderer API](/api/custom-renderer) per creare targeting renderer personalizzati [WebGL](https://troisjs.github.io/) o anche per [il terminale](https://github.com/vue-te
sistemato

2023-10-12 21:24 UTC, phox081 commented on src/guide/extras/animation.md
> +## Animazione con gli osservatori {#animating-with-watchers}
è rimasto "osservatori"

2023-10-12 21:24 UTC, phox081 commented on src/guide/extras/animation.md
> +Oltre al colore, puoi anche utilizzare le associazioni di stile per animare la trasformazione, la larghezza o l'altezza di un elemento. Puoi anche animare percorsi SVG utilizzando la conformazione ve
manca binding

2023-10-12 21:24 UTC, phox081 commented on src/guide/extras/animation.md
> +
sembra ci sia ancora: "Alcuni effetti di transizione...." dovrebbe essere al rigo 93

2023-10-12 21:26 UTC, phox081 requested changes
@andreacampaci perdonami, forse con tutti i cambi è saltato qualcosa: non vedo tutte le modifiche al file animation, eliminando la riga 93 dovrebbe sistemarsi il disallineamento e mancano binding e il titolo per i watcher. Per gli altri file tutto ok.

2023-10-15 18:20 UTC, phox081 approved these changes

2023-10-15 18:26 UTC, merged

2023-10-15 18:27 UTC, phox081 commented
Lascio il Br per ora attivo